AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mandrake

  SAM for Mandrake App

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    

Resources:
  LambdaListAll:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mandrake/
      Handler: app.lambda_main
      Runtime: python3.7
      Events:
        GettoWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mysfits
            Method: get
      Policies: 
      - AmazonDynamoDBFullAccess
  
  LambdaPutEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mandrake/
      Handler: app.write_event
      Runtime: python3.7
      Events:
        WriteEvent:
          Type: Api
          Properties:
            Path: /puto 
            Method: put

  LambdaDefault:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mandrake/
      Handler: app.defoe
      Runtime: python3.7
      Events:
        WriteEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      Policies:
        - AmazonDynamoDBFullAccess


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TheApi:
    Description: "API Gateway endpoint URL for Prod stage for the function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/all/"
  LambdaListAll:
    Description: "Lambda Function ListAll ARN"
    Value: !GetAtt LambdaListAll.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Lambda"
    Value: !GetAtt LambdaListAllRole.Arn
